"""Added supplier column to Inventory

Revision ID: 93bd764fe394
Revises: f5d9a3a97e6b
Create Date: 2025-02-25 11:36:45.086714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bd764fe394'
down_revision = 'f5d9a3a97e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('supplier')

    # ### end Alembic commands ###
